table 'dim Promotion'
	lineageTag: 4370317a-49d2-4bc8-93fe-22ca30bc0f63

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 03678feb-7bf4-4097-b7f0-1e1ce9d76037
		summarizeBy: none
		sourceColumn: PromotionKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PromotionLabel
		dataType: string
		lineageTag: f65d3eb2-3584-4cd9-99e2-3f4e33bd927a
		summarizeBy: none
		sourceColumn: PromotionLabel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PromotionName
		dataType: string
		lineageTag: 5a461487-f60c-4d35-a60d-4d804e794bc8
		summarizeBy: none
		sourceColumn: PromotionName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PromotionDescription
		dataType: string
		lineageTag: a944160b-23cf-41e1-9c2b-2f08c969beaf
		summarizeBy: none
		sourceColumn: PromotionDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DiscountPercent
		dataType: double
		lineageTag: 37e2e54f-72bb-4802-bb45-088731872d5c
		summarizeBy: none
		sourceColumn: DiscountPercent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PromotionType
		dataType: string
		lineageTag: ec467865-3a1f-45b1-99fa-87680382761e
		summarizeBy: none
		sourceColumn: PromotionType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PromotionCategory
		dataType: string
		lineageTag: 262a989b-f350-4996-b08f-b3b0ed2976a4
		summarizeBy: none
		sourceColumn: PromotionCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MinQuantity
		dataType: int64
		formatString: 0
		lineageTag: 40c748e9-2542-40ba-947a-224c5cad99ba
		summarizeBy: none
		sourceColumn: MinQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MaxQuantity
		dataType: int64
		formatString: 0
		lineageTag: 954514d3-0a37-4a28-ba3d-c9e93a08d7a3
		summarizeBy: none
		sourceColumn: MaxQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 6e060bfd-54cb-4a7b-8e64-3a64f0ebead0
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column EndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 58eacd24-6493-4c1e-b689-2a3741abcd6f
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'dim Promotion' = m
		mode: import
		queryGroup: 02_Dimentions
		source =
				let
				    Source = Sql.Database("localhost\SQLEXPRESS", "ContosoRetailDW"),
				    dbo_DimPromotion = Source{[Schema="dbo",Item="DimPromotion"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimPromotion,{"LoadDate", "UpdateDate", "ETLLoadID"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Custom Start Date", each Date.AddYears([StartDate],16)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Custom Start Date", type date}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type", "Custom EndDate", each Date.AddYears([EndDate],16)),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Custom EndDate", type date}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"StartDate", "EndDate"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns1",{"PromotionKey", "PromotionLabel", "PromotionName", "PromotionDescription", "DiscountPercent", "PromotionType", "PromotionCategory", "Custom Start Date", "Custom EndDate", "MinQuantity", "MaxQuantity", "FactOnlineSales", "FactSales"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Custom Start Date", "StartDate"}, {"Custom EndDate", "EndDate"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

