table 'dim Currency'
	lineageTag: d70ee3be-f35c-4051-ba37-68494cca907a

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: a8863f31-50ee-464b-9bab-bfcaf6f8a030
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyLabel
		dataType: string
		lineageTag: 15543558-b58e-4c31-b2fa-fe2e897c7d68
		summarizeBy: none
		sourceColumn: CurrencyLabel

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: 33aad077-2643-4ea1-9be2-347416b82ca1
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	column CurrencyDescription
		dataType: string
		lineageTag: db85a9d1-7cbb-4b34-8ee6-c8e4c6be4ede
		summarizeBy: none
		sourceColumn: CurrencyDescription

		annotation SummarizationSetBy = Automatic

	column ETLLoadID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9971a929-69c9-4ec9-99fa-c43e57635370
		summarizeBy: count
		sourceColumn: ETLLoadID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpdateDate
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: b6815c65-23f9-46de-9350-8a3971a09e89
		summarizeBy: none
		sourceColumn: UpdateDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'dim Currency' = m
		mode: import
		queryGroup: 02_Dimentions
		source =
				let
				    Source = Sql.Database("localhost\SQLEXPRESS", "ContosoRetailDW"),
				    dbo_DimCurrency = Source{[Schema="dbo",Item="DimCurrency"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimCurrency,{"LoadDate", "FactInventory", "FactOnlineSales", "FactSales", "FactSalesQuota", "FactStrategyPlan", "FactExchangeRate"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

