table 'dim Geo'
	lineageTag: d4097577-1262-4dcb-84ac-3533b0dd3853

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: c8f1f4b6-4017-4f5e-9a3a-0cccb676110c
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column GeographyType
		dataType: string
		lineageTag: f7ea45ba-84a1-4c48-b9d4-d39320027024
		summarizeBy: none
		sourceColumn: GeographyType

		annotation SummarizationSetBy = Automatic

	column ContinentName
		dataType: string
		lineageTag: 3e57141e-089d-4eae-bf72-c78e5b3eb62a
		dataCategory: Continent
		summarizeBy: none
		sourceColumn: ContinentName

		annotation SummarizationSetBy = Automatic

	column CityName
		dataType: string
		lineageTag: 061385db-09f9-4bf1-9081-77fbe32baee9
		dataCategory: City
		summarizeBy: none
		sourceColumn: CityName

		annotation SummarizationSetBy = Automatic

	column StateProvinceName
		dataType: string
		lineageTag: 0ebeb041-dbbe-427a-aef6-f63ff62c5a9b
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: StateProvinceName

		annotation SummarizationSetBy = Automatic

	column RegionCountryName
		dataType: string
		lineageTag: 40f4c4ec-1e09-4158-83cc-d34408c3984c
		dataCategory: Country
		summarizeBy: none
		sourceColumn: RegionCountryName

		annotation SummarizationSetBy = Automatic

	hierarchy 'Continent Hierarchy'
		lineageTag: 43a4876c-6018-4c62-8c2b-98dee7b1dbea

		level StateProvinceName
			lineageTag: 3590aafa-5652-4560-bd7d-4c7dfb586491
			column: StateProvinceName

		level ContinentName
			lineageTag: 97d82320-7047-4f80-80ce-cc094c05d2b6
			column: ContinentName

		level RegionCountryName
			lineageTag: e7a47da2-0941-4ba5-9d0b-056c2b4661fe
			column: RegionCountryName

		level CityName
			lineageTag: 3ea64258-94a7-4b09-8981-bfc727c7e061
			column: CityName

	partition 'dim Geo' = m
		mode: import
		queryGroup: 02_Dimentions
		source =
				let
				    Source = #"dim Geo original",
				    #"Removed Columns" = Table.RemoveColumns(Source,{"ETLLoadID", "UpdateDate", "DimCustomer", "DimSalesTerritory", "Geometry", "LoadDate"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

